### PR TITLE
Three issues solved

### PR DESCRIPTION
**Pull request by ricdays**
Repair timers issue solved
Goal button active issue solved
Font Crysta replaced by LED and LCDM

### CODE REVIEW

**Comment by jveijck** [comment]
Hi,

How do I get this version on my laptop?
which git command do I have to use ?by
git pull does not work.
I would like to test with the version tomorrow (19 march). Then the new
version can be tested by RobotSports, Falcons and TechUnited

With best regards,

Jurge

2016-03-18 17:13 GMT+01:00 Ricardo Dias notifications@github.com:

> Repair timers issue solved
> Goal button active issue solved
> 
> ## Font Crysta replaced by LED and LCDM
> 
> You can view, comment on, or merge this pull request online at:
> 
>   https://github.com/RoboCup-MSL/RefBox2015/pull/6
> Commit Summary
> - Changes made in Munique.
> - Merge branch 'master' of https://github.com/BernardoCunha/RefBox2015
> 
> File Changes
> - _M_ mslrb2015/Button.pde
>   https://github.com/RoboCup-MSL/RefBox2015/pull/6/files#diff-0 (13)
> - _M_ mslrb2015/Comms.pde
>   https://github.com/RoboCup-MSL/RefBox2015/pull/6/files#diff-1 (34)
> - _M_ mslrb2015/Log.pde
>   https://github.com/RoboCup-MSL/RefBox2015/pull/6/files#diff-2 (3)
> - _M_ mslrb2015/Misc.pde
>   https://github.com/RoboCup-MSL/RefBox2015/pull/6/files#diff-3 (10)
> - _M_ mslrb2015/RefreshButon.pde
>   https://github.com/RoboCup-MSL/RefBox2015/pull/6/files#diff-4 (64)
> - _M_ mslrb2015/Robot.pde
>   https://github.com/RoboCup-MSL/RefBox2015/pull/6/files#diff-5 (6)
> - _M_ mslrb2015/ScoreClients.pde
>   https://github.com/RoboCup-MSL/RefBox2015/pull/6/files#diff-6 (2)
> - _M_ mslrb2015/StateMachine.pde
>   https://github.com/RoboCup-MSL/RefBox2015/pull/6/files#diff-7 (28)
> - _M_ mslrb2015/SystemEvents.pde
>   https://github.com/RoboCup-MSL/RefBox2015/pull/6/files#diff-8 (6)
> - _M_ mslrb2015/Team.pde
>   https://github.com/RoboCup-MSL/RefBox2015/pull/6/files#diff-9 (31)
> - _M_ mslrb2015/enums.java
>   https://github.com/RoboCup-MSL/RefBox2015/pull/6/files#diff-10 (32)
> - _M_ mslrb2015/mslrb2015.pde
>   https://github.com/RoboCup-MSL/RefBox2015/pull/6/files#diff-11 (45)
> 
> Patch Links:
> - https://github.com/RoboCup-MSL/RefBox2015/pull/6.patch
> - https://github.com/RoboCup-MSL/RefBox2015/pull/6.diff
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> https://github.com/RoboCup-MSL/RefBox2015/pull/6

## 

Jürge van Eijck

Barba Trick Consulting
't Vunderke 15
5066 XV Moergestel
The Netherlands
Phone: +31 13 - 54 54 164
Mobile: +31 6 - 427 444 00
e-mail: Jurge@barbatrick.nl
www: www.barbatrick.nl

**Comment by ricdays** [comment]
Hello Jurge,

Many thanks for your interest in testing these changes!
Bernardo made a "fork" of the repository and this is a pull request to integrate his changes into the master branch of the official repo. This is the normal workflow when you want to contribute to an open-source project in github - and git in general :)

So, if you pull from the official repo, it won't work, because these changes are not here yet. You have to pull from Bernardo Cunha's fork:
https://github.com/BernardoCunha/RefBox2015.git

I hope this helps, and do not hesitate in contacting if you have further questions :)

Best regards,
Ricardo

**Comment by jveijck** [comment]
Hi Ricardo,

The version is not working due to missing fonts (i am using processing 3):

Listening for transport dt_socket at address: 8662
Use surface.setTitle() instead of frame.setTitle in Processing 3
The font "fonts/LCDM.TTF" is missing or inaccessible, make sure the URL is
valid or that the file has been added to your sketch and is readable.
The font "fonts/LED.ttf" is missing or inaccessible, make sure the URL is
valid or that the file has been added to your sketch and is readable.
This IP: 127.0.1.1

Probably some files must be added.
The previous version is working fine for me.

Best regards,

Jurge

2016-03-19 0:07 GMT+01:00 Ricardo Dias notifications@github.com:

> Hello Jurge,
> 
> Many thanks for your interest in testing these changes!
> Bernardo made a "fork" of the repository and this is a pull request to
> integrate his changes into the master branch of the official repo. This is
> the normal workflow when you want to contribute to an open-source project
> in github - and git in general :)
> 
> So, if you pull from the official repo, it won't work, because these
> changes are not here yet. You have to pull from Bernardo Cunha's fork:
> https://github.com/BernardoCunha/RefBox2015.git
> 
> I hope this helps, and do not hesitate in contacting if you have further
> questions :)
> 
> Best regards,
> Ricardo
> 
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> https://github.com/RoboCup-MSL/RefBox2015/pull/6#issuecomment-198575098

## 

Jürge van Eijck

Barba Trick Consulting
't Vunderke 15
5066 XV Moergestel
The Netherlands
Phone: +31 13 - 54 54 164
Mobile: +31 6 - 427 444 00
e-mail: Jurge@barbatrick.nl
www: www.barbatrick.nl

**Comment by ricdays** [comment]
This RefBox was done in Processing v2 (I'm not sure if everything runs smoothly on version 3).
Regarding the problem, the font files seem to be missing... We will take care of it ASAP.

**Comment by jveijck** [comment]
Hi Ricardo,

I tested the previous version with processing 3.0 without any problem.
I was able to create a binary for my team. We used that for testing.
If the font issue is solved today, I might test it during a mini-game.
This afternoon the dutch 3 team will play some games as preparation of the
European open.

Jurge

2016-03-19 0:59 GMT+01:00 Ricardo Dias notifications@github.com:

> This RefBox was done in Processing v2 (I'm not sure if everything runs
> smoothly on version 3).
> Regarding the problem, the font files seem to be missing... We will take
> care of it ASAP.
> 
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> https://github.com/RoboCup-MSL/RefBox2015/pull/6#issuecomment-198587583

## 

Jürge van Eijck

Barba Trick Consulting
't Vunderke 15
5066 XV Moergestel
The Netherlands
Phone: +31 13 - 54 54 164
Mobile: +31 6 - 427 444 00
e-mail: Jurge@barbatrick.nl
www: www.barbatrick.nl

**Comment by ricdays** [comment]
@jveijck I'm sorry we haven't yet uploaded the fonts.
I'm wondering if you used the current master version on your preparation matches.
If yes, did you run into any problem? If yes, please create issues so that we can solve them during the next two weeks.

**Comment by jveijck** [comment]
Hi Ricardo,

I was to late at the game for the preparations. The refbox was not used.
In our own gui there was a bug (goalMagenta iso goalkickMagenta).
I will explicit request to test the coming week with Refbox2015 (iso own
gui).

Jurge

2016-03-20 20:57 GMT+01:00 Ricardo Dias notifications@github.com:

> @jveijck https://github.com/jveijck I'm sorry we haven't yet uploaded
> the fonts.
> I'm wondering if you used the current master version on your preparation
> matches.
> If yes, did you run into any problem? If yes, please create issues so that
> we can solve them during the next two weeks.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> https://github.com/RoboCup-MSL/RefBox2015/pull/6#issuecomment-199006128

## 

Jürge van Eijck

Barba Trick Consulting
't Vunderke 15
5066 XV Moergestel
The Netherlands
Phone: +31 13 - 54 54 164
Mobile: +31 6 - 427 444 00
e-mail: Jurge@barbatrick.nl
www: www.barbatrick.nl

**Comment by BernardoCunha** [comment]
Fonts LED and LCDM have been added to my fork.

Best

Bernardo

**Comment by jveijck** [comment]
Hi Ricardo,

I checked out the version 0.92 beta (after merge #6).
This version works fine for me. The problem with the fonts are solved.
I created a new linux export and pushed it to my team.

I am busy to create a more extensive manual for the refbox, but i will be
ready after the European Open.
I hope to speak to you in Eindhoven, to share some ideas.

Par example: the original refbox had a xml protocol, that is not widely
used. The advantage of the protocol (2010) was that it contain
more information than in the character protocol2009. I propose to add a new
rich protocol (2016/2017) which should be JSON-based and point-to-point
(like the 2009 protocol). Information like: stand (score), time left and
players who received cards can be adapted in the game play by the teams.

The card administration in refbox2015 is different than in the old refbox.
In the old refbox cards are awarded per player. Now it seems that the card
is award to a team. After two yellow cards any player must leave the field.
(I didn't look up in the rules what the current rules are).

Jurge

2016-03-21 15:10 GMT+01:00 Ricardo Dias notifications@github.com:

> Merged #6 https://github.com/RoboCup-MSL/RefBox2015/pull/6.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> https://github.com/RoboCup-MSL/RefBox2015/pull/6#event-597177726

## 

Jürge van Eijck

Barba Trick Consulting
't Vunderke 15
5066 XV Moergestel
The Netherlands
Phone: +31 13 - 54 54 164
Mobile: +31 6 - 427 444 00
e-mail: Jurge@barbatrick.nl
www: www.barbatrick.nl

**Pull request merged**
